spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jdbc-url: jdbc:mysql://localhost:3306/dev_test?useUnicode=yes&characterEncoding=UTF-8

logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:
        type:
          descriptor:
            sql:
              BasicBinder=TRACE: