spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: com.jiaochuan.hazakura.service.CustomMariaDB53Dialect
server:
  servlet:
    session:
      timeout: 2h
springdoc:
  packages-to-scan: com.jiaochuan.hazakura
