spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edw7tk0quska0chz
    password: dsqyzn6v9l783vem
    url: jdbc:mysql://dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ein8lddp2557gv5n?useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
