spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: com.jiaochuan.hazakura.service.CustomMariaDB53Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    session:
      timeout: 2h
springdoc:
  packages-to-scan: com.jiaochuan.hazakura
  swagger-ui:
    disable-swagger-default-url: false
